# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-pvc-hostpath
# spec:
#   provisioner: kubernetes.io/no-provisioner
#   reclaimPolicy: Retain
#   volumeBindingMode: WaitForFirstConsumer
#   allowVolumeExpansion: true
#   mountOptions:
#     - "noexec,nosuid"

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
