apiVersion: v1
kind: Secret
metadata:
  name: pg-creds
  namespace: git
type: Opaque
stringData:
  DB_ROOT_USERNAME: "CHANGE_ME"
  DB_ROOT_PASSWORD: "CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: forgejo-creds
  namespace: git
type: Opaque
stringData:
  DB_HOST: "forgejo-pg-svc:5432"
  DB_DATABASE: "CHANGE_ME"
  DB_USER: "CHANGE_ME"
  DB_PASSWORD: "CHANGE_ME"

  LFS_JWT_SECRET: "CHANGE_ME"
  SECRET_KEY: "CHANGE_ME"
  INTERNAL_TOKEN: "CHANGE_ME"
