apiVersion: v1
kind: Secret
metadata:
  name: pg-creds
  namespace: git
type: Opaque
stringData:
  DB_ROOT_USERNAME: "CHANGE_ME"
  DB_ROOT_PASSWORD: "CHANGE_ME"
  POSTGRES_DB: "CHANGE_ME"
  POSTGRES_USER: "CHANGE_ME"
  POSTGRES_PASSWORD: "CHANGE_ME"
