version: '3.8'

networks:
  proxy-network:
    name: proxy-network
    driver: bridge
  gitea-network:
    name: gitea-network
    driver: bridge
  matrix-network:
    name: matrix-network
    driver: bridge