apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-cfm
  namespace: matrix
data:
  init.sql: |
    -- Synapse database & user
    CREATE DATABASE ${MX_DB_NAME}
      WITH ENCODING='UTF8'
           LC_COLLATE='C'
           LC_CTYPE='C'
           TEMPLATE=template0;
    CREATE USER ${MX_DB_USERNAME} WITH PASSWORD '${MX_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${MX_DB_NAME} TO ${MX_DB_USERNAME};
    \c ${MX_DB_NAME}
    CREATE SCHEMA ${MX_DB_USERNAME} AUTHORIZATION ${MX_DB_USERNAME};
    ALTER USER ${MX_DB_USERNAME} SET search_path TO ${MX_DB_USERNAME}, public;

    -- MAS database & user
    CREATE DATABASE ${MAS_DB_NAME}
      WITH ENCODING='UTF8'
           LC_COLLATE='C'
           LC_CTYPE='C'
           TEMPLATE=template0;
    CREATE USER ${MAS_DB_USERNAME} WITH PASSWORD '${MAS_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${MAS_DB_NAME} TO ${MAS_DB_USERNAME};
    \c ${MAS_DB_NAME}
    GRANT ALL ON SCHEMA public TO ${MAS_DB_USERNAME};
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MAS_DB_USERNAME} IN SCHEMA public
      GRANT ALL ON TABLES TO ${MAS_DB_USERNAME};
    ALTER DEFAULT PRIVILEGES FOR ROLE ${MAS_DB_USERNAME} IN SCHEMA public
      GRANT ALL ON SEQUENCES TO ${MAS_DB_USERNAME};
