apiVersion: v1
kind: ConfigMap
metadata:
  name: mas-cfm
  namespace: matrix
data:
  config.yaml: |
    http:
      public_base: "https://auth.k8s.test/"
      issuer: "https://auth.k8s.test/"
      listeners:
        - name: web
          resources:
            - name: discovery
            - name: human
            - name: oauth
            - name: compat
            - name: graphql
            - name: assets
          binds:
            - address: "0.0.0.0:8080"
          proxy_protocol: false
        - name: internal
          resources:
            - name: health
          binds:
            - address: "0.0.0.0:8081"
      trusted_proxies:
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 10.0.0.0/8
        - 127.0.0.1/8
    database:
      uri: postgresql://postgres-svc/mas
      max_connections: 10
    passwords:
      enabled: true
      schemes:
        - version: 1
          algorithm: argon2id
    matrix:
      kind: synapse
      homeserver: "k8s.test"
      endpoint: "http://synapse-svc:8008/"
