version: '3.8'

services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    networks:
      - proxy-network
    restart: always
    expose:
      - 1883
      - 9001
    volumes:
      - ./mqtt/.data/:/mosquitto/data/:rw
      - ./mqtt/.logs/:/mosquitto/log/:rw
      - ./mqtt/.config/:/mosquitto/config/:r
    labels:
      traefik.enable: true

      traefik.http.routers.mqtt.rule: Host(`mqtt.${DOMAIN_NAME:-localhost}`)
      traefik.http.routers.mqtt.entrypoints: websecure

      traefik.tcp.routers.mqtt.rule: HostSNI(`*`)
      traefik.tcp.services.mqtt.loadbalancer.server.port: 8883
      
      traefik.tcp.routers.mqtt.entrypoints: mqtt

      traefik.http.services.mqtt.loadbalancer.server.port: 9001
      traefik.docker.network: public_facing