version: '3.8'

services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    networks:
      - proxy-network
    restart: always
    expose:
      - 1883
      - 9001
    volumes:
      - ./mqtt/.data/:/mosquitto/data/:rw
      - ./mqtt/.logs/:/mosquitto/log/:rw
      - ./mqtt/.config/:/mosquitto/config/:r
    labels:
      traefik.enable: true

      traefik.tcp.routers.mqtt.rule: HostSNI(`mqtt.${DOMAIN_NAME:-localhost}`)
      traefik.tcp.routers.mqtt.entrypoints: mqtt
      traefik.tcp.routers.mqtt.tls: true
      traefik.tcp.routers.mqtt.tls.certresolver: letsencryptresolver
      traefik.tcp.services.mqtt.loadbalancer.server.port: 1883
      
      

      traefik.http.routers.mqtt.rule: Host(`mqtt.${DOMAIN_NAME:-localhost}`)
      traefik.http.routers.mqtt.entrypoints: websocket
      traefik.http.routers.mqtt.tls: true
      traefik.http.routers.mqtt.tls.certresolver: letsencryptresolver
      traefik.http.services.mqtt.loadbalancer.server.port: 9001