version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    env_file:
      - gitea/.config/gitea.env
    restart: always
    networks:
      - gitea-network
    volumes:
      - ./gitea/.data/:/data:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 3000
    depends_on:
      - postgres_db