apiVersion: v1
kind: Namespace
metadata:
  name: headlamp
  labels:
    name: headlamp
    team: personal
    environment: homelab
    app.kubernetes.io/managed-by: gitops
    role: cluster-dashboard
