apiVersion: v1
kind: PersistentVolume
metadata:
  name: synapse-pvl
  namespace: matrix-dot-org
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/k8s/matrix-dot-org/synapse
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pvc
  namespace: matrix-dot-org
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
