apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-data-pvc
  namespace: matrix-dot-org
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: local-path
