apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-dpl
  namespace: matrix-dot-org
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      initContainers:
        - name: render-config
          image: alpine:latest
          command:
            - sh
            - -c
            - "apk add --no-cache gettext && envsubst < /tmp/template/homeserver.yaml > /tmp/config/homeserver.yaml"
          envFrom:
            - secretRef:
                name: matrix-secrets
          volumeMounts:
            - name: synapse-config
              mountPath: /tmp/template
            - name: synapse-config-rendered
              mountPath: /tmp/config
      containers:
        - name: synapse
          image: matrixdotorg/synapse:latest
          ports:
            - containerPort: 8008
          envFrom:
            - secretRef:
                name: matrix-secrets
          volumeMounts:
            - name: synapse-data
              mountPath: /data
            - name: synapse-config-rendered
              mountPath: /data/homeserver.yaml
              subPath: homeserver.yaml
            - name: synapse-config
              mountPath: /data/freezlex.dev.log.config
              subPath: freezlex.dev.log.config
      volumes:
        - name: synapse-config
          configMap:
            name: synapse-cfm
        - name: synapse-data
          persistentVolumeClaim:
            claimName: synapse-pvc
        - name: synapse-config-rendered
          emptyDir: {}
