apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-dpl
  namespace: matrix-dot-org
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      containers:
        - name: synapse
          image: matrixdotorg/synapse:latest
          env:
            - name: SYNAPSE_CONFIG_PATH
              value: "/data/homeserver.yaml"
            - name: VIRTUAL_HOST
              value: "freezlex.dev"
          ports:
            - containerPort: 8008
          volumeMounts:
            - name: synapse-data
              mountPath: /data
            - name: synapse-config
              mountPath: /data/homeserver.yaml
              subPath: homeserver.yaml
      volumes:
        - name: synapse-config
          configMap:
            name: synapse-cfm
        - name: synapse-data
          persistentVolumeClaim:
            claimName: synapse-pvc
