apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-cfm
  namespace: matrix
data:
  homeserver.yaml: |
    server_name: "polarys.im"
    pid_file: /data/homeserver.pid
    listeners:
      - port: 8008
        tls: false
        type: http
        x_forwarded: true
        resources:
          - names: [client, federation]
            compress: false
    database:
      name: psycopg2
      args:
        user: ${MX_DB_USERNAME}
        password: ${MX_DB_PASSWORD}
        dbname: ${MX_DB_NAME}
        host: pg-svc
        port: 5432
        cp_min: 5
        cp_max: 10
    log_config: "/config/polarys.im.log.config"
    media_store_path: /data/media_store
    registration_shared_secret: "${MX_REGISTRATION_SECRET}"
    macaroon_secret_key: "${MX_MACAROON_SECRET}"
    form_secret: "${MX_FORM_SECRET}"
    signing_key_path: "/keys/polarys.im.signing.key"
    trusted_key_servers:
      - server_name: "matrix.org"
    password_config:
      enabled: false
    matrix_authentication_service:
      enabled: true
      endpoint: "http://mas/"
      secret: "${MX_MAS_EXCHANGE_TOKEN}"
    report_stats: true
    experimental_features:
      msc3266_enabled: true
      msc4140_enabled: true
      msc4108_enabled: true
      msc4143_enabled: true
    livekit:
      service_url: "http://livekit-jwt:8080"
    server_notices:
        system_mxid_localpart: server
        system_mxid_display_name: "Polarys"
        room_name: "Polarys | Server Notice"
        room_topic: "Room used by your server admin to notice you of important information"
        auto_join: true

  log.config: |
    version: 1
    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: precise
      buffer:
        class: synapse.logging.handlers.PeriodicallyFlushingMemoryHandler
        target: console
        capacity: 10
        flushLevel: 30
        period: 5
    loggers:
      synapse.storage.SQL:
        level: WARN
    root:
      level: INFO
      handlers: [buffer]
    disable_existing_loggers: false
