apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      securityContext:
        fsGroup: 991

      initContainers:
        - name: render-config
          image: alpine:3.21
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              apk add --no-cache gettext
              envsubst < /tmp/homeserver.yaml > /data/homeserver.yaml
              chown 991:991 /data/homeserver.yaml
              echo "homeserver.yaml rendered."
          envFrom:
            - secretRef:
                name: matrix-creds
          volumeMounts:
            - name: synapse-data
              mountPath: /data
            - name: synapse-config
              mountPath: /tmp
              readOnly: true

      containers:
        - name: synapse
          image: matrixdotorg/synapse:latest
          securityContext:
            runAsUser: 991
            runAsGroup: 991
            allowPrivilegeEscalation: false
          ports:
            - name: http
              containerPort: 8008
          envFrom:
            - secretRef:
                name: matrix-creds
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          startupProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: synapse-data
              mountPath: /data
            - name: synapse-keys
              mountPath: /data/polarys.im.signing.key
              subPath: polarys.im.signing.key
            - name: synapse-config
              mountPath: /data/polarys.im.log.config
              subPath: log.config

      volumes:
        - name: synapse-data
          persistentVolumeClaim:
            claimName: synapse-pvc
        - name: synapse-keys
          persistentVolumeClaim:
            claimName: synapse-keys-pvc
        - name: synapse-config
          configMap:
            name: synapse-cfm
