apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse-dpl
  namespace: matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      volumes:
        - name: synapse-data
          persistentVolumeClaim:
            claimName: synapse-pvc
        - name: synapse-config
          configMap:
            name: synapse-cfm

      securityContext:
        fsGroup: 991

      initContainers:
        - name: render-config
          image: alpine:latest
          securityContext:
            runAsUser: 0
          command:
            - sh
            - -c
            - |
              # On vérifie si le fichier existe déjà sur le PV
              if [ ! -f /data/homeserver.yaml ]; then
                echo "Cannot find 'homeserver.yaml' on disk. Initial generation..."
                apk add --no-cache gettext
                envsubst < /tmp/homeserver.yaml > /data/homeserver.yaml
                chown -R 991:991 /data
                echo "Succesfully generated 'homeserver.yaml'."
              else
                echo "The 'homeserver.yaml' file already exists on disk. Initial file generation skipped."
              fi
          envFrom:
            - secretRef:
                name: matrix-secrets
          volumeMounts:
            - name: synapse-data
              mountPath: /data
            - name: synapse-config
              mountPath: /tmp

      containers:
        - name: synapse
          image: matrixdotorg/synapse:latest
          securityContext:
            runAsUser: 991
          ports:
            - containerPort: 8008
          envFrom:
            - secretRef:
                name: matrix-secrets
          volumeMounts:
            - name: synapse-data
              mountPath: /data
            - name: synapse-config
              mountPath: /data/k8s.test.log.config
              subPath: logger-config
