globalArguments:
  - --global.sendanonymoususage=false
  - --global.checknewversion=true
additionalArguments:
  - --serversTransport.insecureSkipVerify=true
  - --log.level=DEBUG
deployment:
  enabled: true
  replicas: 1
  annotations: {}
  podAnnotations: {}
  additionalContainer: []
  initContainers: []
ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true
ingressRoute:
  dashboard:
    enabled: false
providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-external
    namespaces:
      - traefik
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: false
rbac:
  enabled: true
service:
  enabled: true
  type: LoadBalancer
  annotation: {}
  labels: {}
  spec:
    loadBalancerIP: 192.168.1.40
  loadBalancerSourceRanges: []
  externalIPs: []
