apiVersion: apps/v1
kind: Deployment
metadata:
  name: synapse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
  template:
    metadata:
      labels:
        app: synapse
    spec:
      containers:
        - name: synapse
          image: matrixdotorg/synapse:v1.46.0
          env:
            - name: SYNAPSE_SERVER_NAME
              value: "freezlex.dev"
            - name: SYNAPSE_REPORT_STATS
              value: "no"
          ports:
            - containerPort: 8008
---
apiVersion: v1
kind: Service
metadata:
  name: synapse
spec:
  ports:
    - port: 8008
      targetPort: 8008
  selector:
    app: synapse
