services:
  mx-synapse:
    container_name: mx-synapse
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    networks:
      - proxy-network
      - database-network
    depends_on:
      - postgres_db
      - traefik
    env_file:
      - ./matrix/.config/mx-synapse.env
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./matrix/.data/:/data:rw
    labels:
      traefik.enable: true
      traefik.http.routers.mx-synapse.rule: "Host(`chat.${DOMAIN_NAME:-localhost}`)"
      traefik.http.routers.mx-synapse.tls: true
      traefik.http.services.gitea.loadbalancer.server.port: 8008
