services:
  mx-synapse:
    container_name: mx-synapse
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
      VIRTUAL_HOST: chat.freezlex.dev
    networks:
      - proxy-network
      - database-network
    depends_on:
      - postgres_db
      - traefik
    healthcheck:
      test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - ./matrix/.data/:/data:rw
    labels:
      traefik.enable: true
      traefik.http.routers.mx-synapse.rule: "Host(`chat.${DOMAIN_NAME:-localhost}`)"
      traefik.http.routers.mx-synapse.tls: true
      traefik.http.routers.mx-synapse.service: mx-synapse
      traefik.http.services.mx-synapse.loadbalancer.server.port: 8008
      # FEDERATION
      traefik.http.routers.mx-synapse-federation.rule: "Host(`${DOMAIN_NAME:-localhost}`)"
      traefik.http.routers.mx-synapse-federation.entrypoints: matrix-federation
      traefik.http.routers.mx-synapse-federation.tls: true
      traefik.http.routers.mx-synapse-federation.service: mx-synapse
      traefik.http.services.mx-synapse-federation.loadbalancer.server.port: 8008
