services:
  dendrite:
    hostname: monolith
    container_name: dendrite
    image: matrixdotorg/dendrite-monolith:${DENDRITE_IMAGE_VERSION:-latest}
    volumes:
      - ./matrix/.config:/etc/dendrite
      - ./matrix/.logs:/etc/dendrite/logs
      - ./matrix/.data/media/:/var/dendrite/media/
    labels:
      - traefik.enable: "TRUE"
      - traefik.http.routers.dendrite.rule: "Host(`matrix.${DOMAIN_NAME:-localhost}`)"
      - traefik.http.routers.dendrite.tls: "TRUE"
    depends_on:
      - postgres
      - traefik
    networks:
      - proxy-network
      - database-network
    restart: unless-stopped