version: '3.8'

services:
  dendrite:
    container_name: dendrite
    image: matrixdotorg/dendrite-monolith:${DENDRITE_IMAGE_VERSION:-latest}
    command: [
      "--tls-cert=server.crt",
      "--tls-key=server.key"
    ]
    ports:
      - 8008:8008
      - 8448:8448
    volumes:
      - ./matrix/.config:/etc/dendrite
      - ./media:/var/dendrite/media
    depends_on:
      - postgres
    networks:
      - matrix-network
    restart: unless-stopped