services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    volumes:
      - ./homepage/.config/:/app/config # Make sure your local config directory exists
      - ./homepage/.logs/:/app/config/logs
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    labels:
      traefik.enable: true
      traefik.http.routers.homepage.rule: "Host(`${DOMAIN_NAME:-localhost}`)"
      traefik.http.services.homepage.loadbalancer.server.port: 3000
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    networks:
      - proxy-network
