apiVersion: v1
kind: Service
metadata:
  name: lk-jwt
  namespace: matrix
spec:
  type: ClusterIP
  selector:
    app: lk-jwt
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: lk
  namespace: matrix
spec:
  type: ClusterIP
  selector:
    app: livekit
  ports:
    - name: http
      port: 7880
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: livekit-media
  namespace: matrix
spec:
  type: LoadBalancer
  selector:
    app: livekit
  ports:
    - name: rtc-udp
      port: 7882
      targetPort: 7882
      protocol: UDP
    - name: rtc-tcp
      port: 7881
      targetPort: 7881
      protocol: TCP
