version: "3"

services:
  languagetool:
    image: erikvl87/languagetool
    container_name: LanguageTool
    restart: always
    environment:
      - langtool_languageModel=/ngrams  # OPTIONAL: Using ngrams data
      - Java_Xms=512m  # OPTIONAL: Setting a minimal Java heap size of 512 mib
      - Java_Xmx=1g    # OPTIONAL: Setting a maximum Java heap size of 1 Gib
    volumes:
      - .languagetool/.data/ngrams:/ngrams
    labels:
      traefik.enable: true
      traefik.http.routers.languagetool.rule: "Host(`languagetool.${DOMAIN_NAME:-localhost}`)"
      traefik.http.services.languagetool.loadbalancer.server.port: 8010