apiVersion: apps/v1
kind: Deployment
metadata:
  name: matrix-postgres
  namespace: matrix-dot-org
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matrix-postgres
  template:
    metadata:
      labels:
        app: matrix-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: matrix-db-secret
                  key: postgres-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-pvc-claim
