apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    name: metallb-system
    team: personal
    environment: homelab
    app.kubernetes.io/managed-by: gitops
    role: loadbalancer
