apiVersion: v1
kind: ConfigMap
metadata:
  name: mas-cfm
  namespace: matrix
data:
  config.yaml: |
    http:
      public_base: "https://auth.polarys.im/"
      issuer: "https://auth.polarys.im/"
      listeners:
        - name: web
          resources:
            - name: discovery
            - name: human
            - name: oauth
            - name: compat
            - name: graphql
            - name: assets
            - name: adminapi
          binds:
            - address: "0.0.0.0:8080"
          proxy_protocol: false
        - name: internal
          resources:
            - name: health
          binds:
            - address: "0.0.0.0:8081"
      trusted_proxies:
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 10.0.0.0/8
        - 127.0.0.1/8
    matrix:
      kind: synapse
      homeserver: "polarys.im"
      endpoint: "http://synapse:8008/"
      secret: "${MX_MAS_EXCHANGE_TOKEN}"
    database:
      host: pg-svc
      port: 5432
      username: ${MAS_DB_USERNAME}
      password: ${MAS_DB_PASSWORD}
      database: ${MAS_DB_NAME}
      max_connections: 10
    account:
      password_registration_enabled: true
      registration_token_required: false
      password_registration_email_required: true
      login_with_email_allowed: true
    passwords:
      enabled: true
      schemes:
        - version: 1
          algorithm: argon2id
    email:
      from: '"Polarys Accounts" <auth@polarys.im>'
      reply_to: '"No reply" <no-reply@polarys.im>'
      transport: smtp
      mode: starttls
      hostname: "${MAS_EMAIL_HOST}"
      port: 587
      username: "${MAS_EMAIL_LOGIN}"
      password: "${MAS_EMAIL_TOKEN}"
    rate_limiting:
      login:
        burst: 5
        per_second: 0.05
      registration:
        burst: 3
        per_second: 0.003
    experimental:
      access_token_ttl: 300
      msc4108_enabled: true
