apiVersion: v1
kind: ConfigMap
metadata:
  name: mas-cfm
  namespace: matrix
data:
  config.yaml: |
    http:
      public_base: "https://auth.julien-ivs.com/"
      issuer: "https://auth.julien-ivs.com/"
      listeners:
        - name: web
          resources:
            - name: discovery
            - name: human
            - name: oauth
            - name: compat
            - name: graphql
            - name: assets
          binds:
            - address: "0.0.0.0:8080"
          proxy_protocol: false
        - name: internal
          resources:
            - name: health
          binds:
            - address: "0.0.0.0:8081"
      trusted_proxies:
        - 192.168.0.0/16
        - 172.16.0.0/12
        - 10.0.0.0/8
        - 127.0.0.1/8
    database:
      host: pg-svc
      port: 5432
      username: ${MAS_DB_USERNAME}
      password: ${MAS_DB_PASSWORD}
      database: ${MAS_DB_NAME}
      max_connections: 10
    account:
      password_registration_enabled: true
      registration_token_required: false
      password_registration_email_required: false
    passwords:
      enabled: true
      schemes:
        - version: 1
          algorithm: argon2id
    experimental:
      access_token_ttl: 300
      msc4108_enabled: true
    matrix:
      kind: synapse
      homeserver: "julien-ivs.com"
      endpoint: "http://synapse:8008/"
      secret: "${MX_MAS_EXCHANGE_TOKEN}"
