apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: proxy
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: websecure
      port: 443
      targetPort: websecure
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: proxy
  labels:
    app: dashboard
spec:
  selector:
    app: traefik
  ports:
    - name: dashboard
      port: 8080
      targetPort: dashboard
