apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashboard-ing
  namespace: reverse-proxy
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dashboard.k8s.test`)
      services:
        - kind: Service
          name: dashboard-svc
          port: 8080
