apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cfm
  namespace: matrix
data:
  init.sql: |
    CREATE DATABASE ${MX_DB_NAME};
    CREATE USER ${MX_DB_USERNAME} WITH PASSWORD '${MX_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${MX_DB_NAME} TO ${MX_DB_USERNAME};
    CREATE DATABASE ${MAS_DB_NAME};
    CREATE USER ${MAS_DB_USERNAME} WITH PASSWORD '${MAS_DB_PASSWORD}';
    GRANT ALL PRIVILEGES ON DATABASE ${MAS_DB_NAME} TO ${MAS_DB_USERNAME};
