apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cfg
  namespace: nginx
data:
  default.conf: |
    server {
      listen 443 ssl;
      server_name localhost;
      root /usr/share/nginx/html;

      location / {
          add_header 'Access-Control-Allow-Origin' '*' always;
          add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
          add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;

          default_type application/json;
      }
    }
  matrix-client: |
    {
      "m.homeserver": { "base_url": "https://matrix.k8s.test" },
      "org.matrix.msc2965.authentication": {
        "issuer": "https://k8s.test",
        "account": "https://auth.k8s.test/"
      }
    }
  matrix-server: |
    { "m.server": "matrix.k8s.test:443" }
  security: |
    Contact: mailto:incidents@k8s.test
    Expires: 2026-12-31T23:59:59.000Z
    Preferred-Languages: fr, en, de
