version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "12G"
    volumes:
      - ./minecraft/.data:/data/:rw
      - ./minecraft/.logs:/data/logs
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.minecraft.rule: 'Host(`mc.${SITE:-localhost}`)'
      traefik.http.services.minecraft.loadbalancer.server.port: 8123
      traefik.tcp.routers.minecraft.rule: HostSNI(`*`)
      traefik.tcp.routers.vanilla.entrypoints: minecraft

    networks:
      - nginx-network