services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    environment:
      EULA: TRUE
      TYPE: FORGE
      VERSION: "1.20.1"
      MEMORY: "12G"
      SERVER_NAME: "Freezlex's Bathtub"
      MOTD: "\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a7c Freezlex's Bathtub\u00a7e \u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7r\n   \u00a79forge\u00a76  |\u00a7e freezlex.dev\u00a76 |\u00a79 1.20.1"
      ICON: "https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/fOlSCTKsGbDEAEPLAwSmXpro"
      MAX_TICK_TIME: -1
      OPS: |
        Freezlex,
        MatheoMC
      WHITELIST: |
        Freezlex,
        CapitaineOurson,
        MatheoMC,
        L1mi3
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_ALLOWED_VERSION_TYPE: beta
      MODRINTH_PROJECTS: |
        bellsandwhistles:uvnfNUsp,
        botarium:O7D6FTfW,
        create:6R069CcK,
        architectury-api:1MKTLiiG,
        create-deco:lcpO5tBr,
        create-railways-navigator:Vb3cssgh,
        create-diesel-generators:R6vueHQB,
        interiors:2wGHT9kO,
        create-new-age:2BEeSV7E,
        create-steam-n-rails:pklcGSDf,
        kotlin-for-forge:hmeyC41q,
        modern-train-parts:ZtrWTdJ1
        decorative-blocks:nGmyeiug
      # Auto-pause server when no one is connected
      ENABLE_AUTOPAUSE: TRUE
    volumes:
      - ./minecraft/.data:/data:rw
      - ./minecraft/.logs/:/data/logs
    restart: unless-stopped
    labels:
      traefik.enable: true
      # TCP Pass through
      traefik.tcp.routers.minecraft.rule: "HostSNI(`*`)"
      traefik.tcp.routers.minecraft.entrypoints: minecraft
      traefik.tcp.services.minecraft.loadbalancer.server.port: 25565
    networks:
      - proxy-network
