services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    environment:
      EULA: TRUE
      TYPE: FORGE
      VERSION: "1.20.1"
      MEMORY: "12G"
      SERVER_NAME: "Freezlex's Bathtub"
      MOTD: "\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a7c Freezlex's Bathtub\u00a7e \u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7r\n  \u00a79vanilla\u00a76 |\u00a7e freezlex.dev\u00a76 |\u00a79 1.20.4"
      ICON: "https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/fOlSCTKsGbDEAEPLAwSmXpro"
      MAX_TICK_TIME: -1
      OPS: |
        Freezlex,
        MatheoMC,
        CaptaineOurson
      WHITELIST: |
        Freezlex,
        CaptaineOurson
        MatheoMC,
        L1mi3
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_ALLOWED_VERSION_TYPE: beta
      MODRINTH_PROJECTS: gJ5afkVv,ZzjhlDgM,sMvUb4Rb,ZM3tt6p1,FTeXqI9v,r4Knci2k,YlOA6mdQ,2u6LRnMa,lhGA9TYQ,84USeAvk,EO8aSHxh,V5ujR2yw,MyfCcqiE
      # Auto-pause server when no one is connected
      ENABLE_AUTOPAUSE: TRUE
    volumes:
      - ./minecraft/.data:/data:rw
      - ./minecraft/.logs/:/data/logs
    restart: unless-stopped
    labels:
      traefik.enable: true
      # TCP Pass through
      traefik.tcp.routers.minecraft.rule: "HostSNI(`*`)"
      traefik.tcp.routers.minecraft.entrypoints: minecraft
      traefik.tcp.services.minecraft.loadbalancer.server.port: 25565
    networks:
      - proxy-network
