version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "12G"
    expose:
      - 25565
      - 8123
    volumes:
      - ./minecraft/.data:/data/:rw
    networks:
      - nginx-network