services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    environment:
      EULA: TRUE
      TYPE: NEOFORGE
      VERSION: "1.21.1"
      MEMORY: "12G"
      SERVER_NAME: "Freezlex's Bathtub"
      MOTD: "\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a7c Freezlex's Bathtub\u00a7e \u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7r\n   \u00a79forge\u00a76  |\u00a7e freezlex.dev\u00a76 |\u00a79 1.20.1"
      ICON: "https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/fOlSCTKsGbDEAEPLAwSmXpro"
      MAX_TICK_TIME: -1
      OPS: |
        Freezlex,
        MatheoMC,
        CapitaineOurson
      WHITELIST: |
        Freezlex,
        CapitaineOurson,
        MatheoMC,
        L1mi3
      MODRINTH_DOWNLOAD_DEPENDENCIES: required
      MODRINTH_ALLOWED_VERSION_TYPE: beta
      MODRINTH_PROJECTS: |
        LNytGWDc:5LpL274U,
        6YfOmC9t:g0S9q7zp,
        L6jvzao4:IJPOCMCt,
        sc9lpPiU:ZyuSyeuy,
        rGWEHQrP:6poGZvvr,
        RgWXq0La:oec4zIe5,
        T21szC0a:WlTXhPfE,
        tu54PMAb:x1Blh0Gt,
        GWFnD2zx:SMSMYsE9,
        Aqlf1Shp:BOq0raqo,
        lhGA9TYQ:ZxYGwlk0,
        9s6osm5g:izKINKFg,
        HsdNFinx:cttRekq9,
        8BmcQJ2H:QEqpUJ1G,
        1eAoo2KR:ACDNgCDA,
        qmCh2PxS:SZm6bDv
      # Auto-pause server when no one is connected
      ENABLE_AUTOPAUSE: TRUE
    volumes:
      - ./minecraft/.data:/data:rw
      - ./minecraft/.logs/:/data/logs
    restart: unless-stopped
    labels:
      traefik.enable: true
      # TCP Pass through
      traefik.tcp.routers.minecraft.rule: "HostSNI(`*`)"
      traefik.tcp.routers.minecraft.entrypoints: minecraft
      traefik.tcp.services.minecraft.loadbalancer.server.port: 25565
    networks:
      - proxy-network
