version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      VERSION: "1.20.4"
      MEMORY: "10G"
      SERVER_NAME: "Freezlex's Bathtub"
      # World Type
      LEVEL_TYPE: FLAT
      GENERATOR_SETTINGS: >-4
          {
              "layers": [
                  {
                      "block": "minecraft:bedrock",
                      "height": 1
                  },
                  {
                      "block": "minecraft:stone",
                      "height": 2
                  },
                  {
                      "block": "minecraft:sandstone",
                      "height": 15
                  }
              ],
              "biome": "minecraft:desert"
          }
      MOTD: "\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500 \u00a7cFreezlex's Bathtub\u00a76 \u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\n   \u00a79vanilla\u00a76  | \u00a7efreezlex.dev\u00a76  | \u00a791.20.4"
      ICON: "https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/fOlSCTKsGbDEAEPLAwSmXpro"
      # Auto-pause server when no one is connected
      ENABLE_AUTOPAUSE: "TRUE"
    volumes:
      - ./minecraft/.data:/data:rw
      - ./minecraft/.logs/:/data/logs
    restart: unless-stopped
    labels:
      traefik.enable: true
      # TCP Pass through
      traefik.tcp.routers.minecraft.rule: 'HostSNI(`*`)'
      traefik.tcp.routers.minecraft.entrypoints: minecraft-tcp
      traefik.tcp.services.minecraft.loadbalancer.server.port: 25565
    networks:
      - proxy-network