services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      VERSION: "1.20.4"
      MEMORY: "10G"
      SERVER_NAME: "Freezlex's Bathtub"
      MAX_TICK_TIME: -1
      OPS: |
        Freezlex,
        MatheoMC
      WHITELIST: |
        Freezlex,
        MatheoMC
      MOTD: "\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a7c Freezlex's Bathtub\u00a7e \u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7r\n  \u00a79vanilla\u00a76 |\u00a7e freezlex.dev\u00a76 |\u00a79 1.20.4"
      ICON: "https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/fOlSCTKsGbDEAEPLAwSmXpro"
      # Auto-pause server when no one is connected
      ENABLE_AUTOPAUSE: "TRUE"
    volumes:
      - ./minecraft/.data:/data:rw
      - ./minecraft/.logs/:/data/logs
    restart: unless-stopped
    labels:
      traefik.enable: true
      # TCP Pass through
      traefik.tcp.routers.minecraft.rule: "HostSNI(`*`)"
      traefik.tcp.routers.minecraft.entrypoints: minecraft
      traefik.tcp.services.minecraft.loadbalancer.server.port: 25565
      # Homepage
      homepage.name: Minecraft
      homepage.href: udp://${DOMAIN_NAME:-localhost}/
      homepage.container: minecraft
      homepage.widget.type: minecraft
      homepage.widget.url: udp://${DOMAIN_NAME:-localhost}/
      homepage.widget.fields[0]: players
      homepage.widget.fields[1]: version
      homepage.widget.fields[2]: status
    networks:
      - proxy-network
