version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "12G"
    volumes:
      - ./minecraft/.data:/data/:rw
      - ./minecraft/.logs:/data/logs
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.minecraft.rule: 'Host(`mc.${DOMAIN_NAME:-localhost}`)'
      traefik.http.services.minecraft.loadbalancer.server.port: 8123
      # TCP Pass through
      traefik.tcp.routers.minecraft.rule: 'HostSNI(`*`)'
      traefik.tcp.routers.minecraft.entrypoints: minecraft
      traefik.tcp.services.minecraft.loadbalancer.server.port: 25565
    networks:
      - proxy-network