version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.19.2"
      MEMORY: "10G"
      SERVER_NAME: "Freezlex's Bathtub"
      MOTD: "\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500 \u00a7cFreezlex's Bathtub\u00a76 \u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\u00a7e\u2b1d\u00a76\u2500\n  \u00a79fabric\u00a76 | \u00a7emc.freezlex.dev\u00a76 | \u00a791.19.2"
      ICON: "https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/CRzKauqCVBnrhwRbcJoFvVgT"
      # Auto-pause server when no one is connected
      ENABLE_AUTOPAUSE: "TRUE"
      MODRINTH_DOWNLOAD_OPTIONAL_DEPENDENCIES: "TRUE"
      MODRINTH_PROJECTS: "fabric-api:hfsU4hXq,create-fabric:q6x0xvc1,terralith:mLdNNka6"
    volumes:
      - ./minecraft/.data:/data:rw
      - ./minecraft/.logs/:/data/logs
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.minecraft.rule: 'Host(`mc.${DOMAIN_NAME:-localhost}`)'
      # TCP Pass through
      traefik.tcp.routers.minecraft.rule: 'HostSNI(`*`)'
      traefik.tcp.routers.minecraft.entrypoints: mc
      traefik.tcp.services.minecraft.loadbalancer.server.port: 25565
    networks:
      - proxy-network