version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:latest
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MEMORY: "8G"
      MOTD: "It's ALIVE !!"
    expose:
      - 25565
    volumes:
      - ./minecraft/.data:/data
    networks:
      - nginx-network