---
- Services:
    - Gitea:
        name: Gitea
        href: https://git.freezlex.dev/
        siteMonitor: https://git.freezlex.dev/
        container: gitea
        widget:
          type: gitea
          key: {{ GITEA_ACCESS_TOKEN }}
          fields: ["notifications", "issues", "pulls"]

    - Minecraft:
        name: Minecraft
        href: udp://freezlex.dev/
        container: minecraft
        widget:
          type: minecraft
          url: udp://freezlex.dev/
          fields: ["players", "version", "status"]

    - Traefik:
        name: Traefik
        href: https://dashboard.freezlex.dev/
        homepage.siteMonitor: https://dashboard.freezlex.dev/
        container: traefik
