---
- Services:
    - Gitea:
        name: Gitea
        href: https://git.freezlex.dev/
        siteMonitor: https://git.freezlex.dev/
        container: gitea
        widget:
          url: http://gitea:3000
          type: gitea
          key: {{HOMEPAGE_VAR_GITEA_KEY}}
          fields: ["notifications", "issues", "pulls"]

    - Minecraft:
        name: Minecraft
        href: udp://freezlex.dev/
        container: minecraft
        widget:
          type: minecraft
          url: udp://freezlex.dev/
          fields: ["players", "version", "status"]

    - Traefik:
        name: Traefik
        href: https://dashboard.freezlex.dev/
        siteMonitor: https://dashboard.freezlex.dev/
        container: traefik