apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-pg-pv
  labels:
    app: postgres
    namespace: git
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data/k8s/forgejo/postgresql
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-pg-pvc
  namespace: git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
