version: '3.9'

services:
  postgres_db:
    image: postgres:14
    restart: always
    container_name: postgres
    env_file:
      - ./postgres/.config/postgres.env
    ports:
      - 5432:5432
    networks:
      - gitea-network
    volumes:
      - ./postgres/.data/:/var/lib/postgresql/data:rw
      - ./postgres/.init/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql