version: '3.9'

services:
  postgres_db:
    image: postgres:14
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea-network
    volumes:
      - ./postgres/.data/:/var/lib/postgresql/data